export const fieldsOfStudy = [
    "Computer Science",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Biomedical Engineering",
    "Aerospace Engineering",
    "Industrial Engineering",
    "Environmental Engineering",
    "Materials Science",
    "Physics",
    "Mathematics",
    "Statistics",
    "Biology",
    "Chemistry",
    "Biochemistry",
    "Neuroscience",
    "Psychology",
    "Economics",
    "Political Science",
    "International Relations",
    "History",
    "English",
    "Philosophy",
    "Sociology",
    "Anthropology",
    "Art History",
    "Music",
    "Theatre",
    "Film",
    "Dance",
    "Architecture",
    "Urban Planning",
    "Landscape Architecture",
    "Environmental Science",
    "Geology",
    "Geography",
    "Astronomy",
    "Astrophysics",
    "Environmental Studies",
    "Public Health",
    "Nursing",
    "Pre-Med",
    "Pre-Law",
    "Business",
    "Finance",
    "Accounting",
    "Marketing",
    "Management",
    "Entrepreneurship",
    "Supply Chain Management",
    "Operations",
    "Human Resources",
    "Other"
] as const